### ISSUE TITLE
eslint 8.5.0 compatibility

### ISSUE THREAD

**Issue by Byron2016** [standard/eslint-config-standard#197] opened 2021-12-21 21:48 UTC
Hi!

Please tell us if eslint-config-standard **is compatible** with the new version of ESlint 8.5.0?

**Comment by nschonni** [comment] 2021-12-22 22:17
Duplicate of https://github.com/standard/eslint-config-standard/issues/192

**Closed** 2021-12-23 00:48 UTC
