### ISSUE TITLE
experimentalObjectRestSpread deprecated

### ISSUE THREAD

**Issue by lili21** [standard/eslint-config-standard#127] opened 2018-08-13 09:47 UTC
```bash
[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
```

**Comment by voxpelli** [comment] 2018-08-13 13:48
Duplicate of #117

An alpha of version 12, which supports ESLint 5, is supported using `npm install eslint-config-standard@next` and tracking of stable release can be found in #123

**Closed** 2018-08-13 14:27 UTC
